/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DocumentNewRouteImport } from './routes/document/new'
import { Route as DocumentUpdateRouteImport } from './routes/document/update'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DocumentIdIndexRouteImport } from './routes/document/$id/index'
import { Route as DocumentIdEditRouteImport } from './routes/document/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentNewRoute = DocumentNewRouteImport.update({
  id: '/document/new',
  path: '/document/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentUpdateRoute = DocumentUpdateRouteImport.update({
  id: '/document/update',
  path: '/document/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentIdIndexRoute = DocumentIdIndexRouteImport.update({
  id: '/document/$id/',
  path: '/document/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentIdEditRoute = DocumentIdEditRouteImport.update({
  id: '/document/$id/edit',
  path: '/document/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/document/new': typeof DocumentNewRoute
  '/document/update': typeof DocumentUpdateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/document/$id/edit': typeof DocumentIdEditRoute
  '/document/$id/': typeof DocumentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/document/new': typeof DocumentNewRoute
  '/document/update': typeof DocumentUpdateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/document/$id/edit': typeof DocumentIdEditRoute
  '/document/$id': typeof DocumentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/document/new': typeof DocumentNewRoute
  '/document/update': typeof DocumentUpdateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/document/$id/edit': typeof DocumentIdEditRoute
  '/document/$id/': typeof DocumentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/document/new'
    | '/document/update'
    | '/api/auth/$'
    | '/document/$id/edit'
    | '/document/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/document/new'
    | '/document/update'
    | '/api/auth/$'
    | '/document/$id/edit'
    | '/document/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/document/new'
    | '/document/update'
    | '/api/auth/$'
    | '/document/$id/edit'
    | '/document/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DocumentNewRoute: typeof DocumentNewRoute
  DocumentUpdateRoute: typeof DocumentUpdateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DocumentIdEditRoute: typeof DocumentIdEditRoute
  DocumentIdIndexRoute: typeof DocumentIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/new': {
      id: '/document/new'
      path: '/document/new'
      fullPath: '/document/new'
      preLoaderRoute: typeof DocumentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/update': {
      id: '/document/update'
      path: '/document/update'
      fullPath: '/document/update'
      preLoaderRoute: typeof DocumentUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$id/': {
      id: '/document/$id/'
      path: '/document/$id'
      fullPath: '/document/$id/'
      preLoaderRoute: typeof DocumentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/$id/edit': {
      id: '/document/$id/edit'
      path: '/document/$id/edit'
      fullPath: '/document/$id/edit'
      preLoaderRoute: typeof DocumentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DocumentNewRoute: DocumentNewRoute,
  DocumentUpdateRoute: DocumentUpdateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DocumentIdEditRoute: DocumentIdEditRoute,
  DocumentIdIndexRoute: DocumentIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
