/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DocumentEditRouteImport } from './routes/document/edit'
import { Route as DocumentNewRouteImport } from './routes/document/new'
import { Route as DocumentUpdateRouteImport } from './routes/document/update'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentEditRoute = DocumentEditRouteImport.update({
  id: '/document/edit',
  path: '/document/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentNewRoute = DocumentNewRouteImport.update({
  id: '/document/new',
  path: '/document/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentUpdateRoute = DocumentUpdateRouteImport.update({
  id: '/document/update',
  path: '/document/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/document/edit': typeof DocumentEditRoute
  '/document/new': typeof DocumentNewRoute
  '/document/update': typeof DocumentUpdateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/document/edit': typeof DocumentEditRoute
  '/document/new': typeof DocumentNewRoute
  '/document/update': typeof DocumentUpdateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/document/edit': typeof DocumentEditRoute
  '/document/new': typeof DocumentNewRoute
  '/document/update': typeof DocumentUpdateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/document/edit'
    | '/document/new'
    | '/document/update'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/document/edit'
    | '/document/new'
    | '/document/update'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/document/edit'
    | '/document/new'
    | '/document/update'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DocumentEditRoute: typeof DocumentEditRoute
  DocumentNewRoute: typeof DocumentNewRoute
  DocumentUpdateRoute: typeof DocumentUpdateRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/edit': {
      id: '/document/edit'
      path: '/document/edit'
      fullPath: '/document/edit'
      preLoaderRoute: typeof DocumentEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/new': {
      id: '/document/new'
      path: '/document/new'
      fullPath: '/document/new'
      preLoaderRoute: typeof DocumentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/update': {
      id: '/document/update'
      path: '/document/update'
      fullPath: '/document/update'
      preLoaderRoute: typeof DocumentUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DocumentEditRoute: DocumentEditRoute,
  DocumentNewRoute: DocumentNewRoute,
  DocumentUpdateRoute: DocumentUpdateRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
